site_name: Weird Java & Kotlin Notes
repo_name: weird-java-kotlin-notes
repo_url: https://github.com/ColstonBod-oy/weird-java-kotlin-notes

theme:
  name: material
  icon:
    logo: octicons/book-24
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.action.view
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/solid/paper-plane
      link: https://mail.google.com/mail/?view=cm&fs=1&to=bodoycolstond@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/ColstonBod-oy
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/colston-bod-oy-60a7521a4/

plugins:
  - search
  - tags

copyright: Copyright &copy; 2024 Colston Bod-oy
