site_name: Weird Java & Kotlin Notes
repo_name: weird-java-kotlin-notes
repo_url: https://github.com/ColstonBod-oy/weird-java-kotlin-notes

theme:
  name: material

use_directory_urls: false

copyright: Copyright &copy; 2024 Colston Bod-oy
